# Generated by Django 5.2.2 on 2025-06-30 23:13

from django.db import migrations

def verify_generic_fks(apps, schema_editor):
    Feed = apps.get_model('core', 'Feed')

    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    for feed in Feed.objects.all():
        # Check translator FK
        if feed.translator_content_type_id:
            try:
                ct = ContentType.objects.get_for_id(feed.translator_content_type_id)
                model_class = apps.get_model(ct.app_label, ct.model)
                if not model_class.objects.filter(pk=feed.translator_object_id).exists():
                    feed.translator_content_type = None
                    feed.translator_object_id = None
            except ContentType.DoesNotExist:
                feed.translator_content_type = None
                feed.translator_object_id = None
        
        # Check summarizer FK
        if feed.summarizer_content_type_id:
            try:
                ct = ContentType.objects.get_for_id(feed.summarizer_content_type_id)
                model_class = apps.get_model(ct.app_label, ct.model)
                if not model_class.objects.filter(pk=feed.summarizer_object_id).exists():
                    feed.summarizer_content_type = None
                    feed.summarizer_object_id = None
            except ContentType.DoesNotExist:
                feed.summarizer_content_type = None
                feed.summarizer_object_id = None
        
        feed.save(update_fields=[
            'translator_content_type', 
            'translator_object_id',
            'summarizer_content_type',
            'summarizer_object_id'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entry'),
        ('translator', '0045_alter_openaitranslator_max_tokens'),
    ]

    operations = [
        migrations.RunPython(verify_generic_fks),
    ]
