# Generated by Django 5.2.2 on 2025-07-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0021_check_empty_engines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.feed'),
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digest Name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL Slug')),
                ('filter_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('filter_prompt', models.TextField(help_text='Custom prompt for filtering entries before digesting.', verbose_name='Filter Prompt')),
                ('digester_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('digest_prompt', models.TextField(help_text='Custom prompt for digesting entries into a summary.', verbose_name='Digest Prompt')),
                ('publish_days', models.CharField(default='1234567', help_text='A string of 7 characters representing days of the week (Mon-Sun), where 1 means Monday, 2 means Tuesday, etc.', max_length=7, verbose_name='Publish Days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used for this digest', verbose_name='Tokens Cost')),
                ('log', models.TextField(blank=True, default='', null=True, verbose_name='Log')),
                ('digester_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digester', to='contenttypes.contenttype')),
                ('filter_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter', to='contenttypes.contenttype')),
                ('related_feeds', models.ManyToManyField(blank=True, related_name='digests', to='core.feed', verbose_name='Related Feeds')),
            ],
            options={
                'verbose_name': 'Digest',
                'verbose_name_plural': 'Digests',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='digest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='core.digest'),
        ),
    ]
