# Generated by Django 5.2.2 on 2025-07-14 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0021_check_empty_engines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.feed'),
        ),
        migrations.CreateModel(
            name='AISummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Report Name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL Slug')),
                ('target_language', models.CharField(choices=[('English', 'English'), ('Chinese Simplified', 'Chinese Simplified'), ('Chinese Traditional', 'Chinese Traditional'), ('Russian', 'Russian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('German', 'German'), ('Spanish', 'Spanish'), ('French', 'French'), ('Indonesian', 'Indonesian'), ('Italian', 'Italian'), ('Hungarian', 'Hungarian'), ('Norwegian Bokmal', 'Norwegian Bokmal'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Swedish', 'Swedish'), ('Turkish', 'Turkish')], default='Chinese Simplified', max_length=50, verbose_name='Language')),
                ('filter_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('filter_prompt', models.TextField(default='\nYou are an advanced RSS content curator. Analyze each article following these protocols:\n\n1. **Cross-article Deduplication**:\n   - Identify duplicate content using semantic similarity\n   - For duplicate sets:\n     • Keep the most comprehensive version\n\n2. **Timeliness Assessment**:\n   • CURRENT: Published <24h (Priority)\n   • STALE: Published 24-72h (Keep only if high-value)\n   • OUTDATED: >72h (Discard unless breakthrough content)\n\n3. **Ad Exclusion**:\n   • Discard if any detected:\n     - Promotional language patterns\n     - Affiliate links\n     - Brand mentions >5% of content\n     - "Sponsored" disclosure\n', help_text='Custom prompt for filtering entries before report generation', verbose_name='Filter Prompt')),
                ('reporter_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('report_prompt', models.TextField(default='Summarize the following text in {target_language} and return markdown format.', help_text='Custom prompt for generating AI summaries report', verbose_name='Report Prompt')),
                ('publish_days', models.CharField(default='1234567', help_text='A string of 7 characters representing days of the week (Mon-Sun), where 1 means Monday, 2 means Tuesday, etc.', max_length=7, verbose_name='Publish Days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used for AI summaries in this report', verbose_name='Total Tokens')),
                ('log', models.TextField(blank=True, default='', null=True, verbose_name='Log')),
                ('filter_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter', to='contenttypes.contenttype')),
                ('related_feeds', models.ManyToManyField(blank=True, related_name='ai_summary_reports', to='core.feed', verbose_name='Related Feeds')),
                ('reporter_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'AI Summary Report',
                'verbose_name_plural': 'AI Summary Reports',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='ai_summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.aisummaryreport'),
        ),
    ]
