# Generated by Django 5.2.4 on 2025-07-28 01:20

import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_check_empty_engines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('target_field', models.CharField(blank=True, choices=[('original_title', 'Original_Title'), ('original_content', 'Original_Content'), ('translated_title', 'Translated_Title'), ('translated_content', 'Translated_Content')], default=['original_content'], help_text='Select the fields to apply the filter on.', null=True, verbose_name='Target Field')),
                ('operation', models.BooleanField(choices=[(True, 'Include - Match only these keywords'), (False, 'Exclude - Exclude that matches these keywords')], default=False, help_text='Action to take on matching keywords.')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filter',
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='filters',
            field=models.ManyToManyField(blank=True, help_text='Filters to apply to the feed entries', null=True, related_name='feeds', to='core.filter', verbose_name='Filters'),
        ),
        migrations.CreateModel(
            name='Tagulous_Filter_keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='filter',
            name='keywords',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Keywords to filter entries. Use comma to separate multiple keywords.', to='core.tagulous_filter_keywords', verbose_name='Keywords'),
        ),
    ]
