# Generated by Django 5.2.2 on 2025-07-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0021_check_empty_engines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.feed'),
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digest Name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL Slug')),
                ('target_language', models.CharField(choices=[('English', 'English'), ('Chinese Simplified', 'Chinese Simplified'), ('Chinese Traditional', 'Chinese Traditional'), ('Russian', 'Russian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('German', 'German'), ('Spanish', 'Spanish'), ('French', 'French'), ('Indonesian', 'Indonesian'), ('Italian', 'Italian'), ('Hungarian', 'Hungarian'), ('Norwegian Bokmal', 'Norwegian Bokmal'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Swedish', 'Swedish'), ('Turkish', 'Turkish')], default='Chinese Simplified', max_length=50, verbose_name='Language')),
                ('filter_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('filter_prompt', models.TextField(default='\nYou are an advanced RSS content curator. Analyze each article following these protocols:\n\n1. **Cross-article Deduplication**:\n   - Identify duplicate content using semantic similarity\n   - For duplicate sets:\n     • Keep the most comprehensive version\n\n2. **Ad Exclusion**:\n   • Discard if any detected:\n     - Promotional language patterns\n     - Affiliate links\n     - Brand mentions >5% of content\n     - "Sponsored" disclosure\n\n3. **Clickbait Detection**\n   Discard if headline:\n   - Uses sensational punctuation (e.g., "SHOCKING!", "You won\'t BELIEVE...")\n   - Poses unanswered questions ("What happened next?")\n   - Employs urgency/scarcity tactics ("Act NOW!")\n\n4. **Content Quality Threshold**\n   Discard if:\n   - Readability score <20 (Flesch-Kincaid)\n   - >10 grammatical errors/100 words\n', help_text='Custom prompt for filtering entries before digesting.', verbose_name='Filter Prompt')),
                ('digester_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('digest_prompt', models.TextField(default='\nROLE: Professional News Editor\nTASK: Generate concise daily briefings\n\n# OUTPUT REQUIREMENTS\n1. FORMAT: Markdown with sections\n2. STRUCTURE:\n   ## {digest_name} | {date}\n   ### category\n   - **[Title](url)**  \n     summary\n\n# CONTENT RULES\n1. SOURCE PRIORITIZATION:\n   - Use existing AI summaries when provided\n   \n2. CATEGORIZATION:\n   - Auto-group articles into 3-5 topics\n\n3. STYLE GUIDELINES:\n   - Active voice, present tense\n   - Highlight:\n     • Novel research\n     • Practical implications\n     • Controversial claims\n   - Never repeat identical phrases\n\n', help_text='', verbose_name='Digest Prompt')),
                ('publish_days', models.CharField(default='1234567', help_text='A string of 7 characters representing days of the week (Mon-Sun), where 1 means Monday, 2 means Tuesday, etc.', max_length=7, verbose_name='Publish Days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used for AI summaries in this digest', verbose_name='Total Tokens')),
                ('log', models.TextField(blank=True, default='', null=True, verbose_name='Log')),
                ('digester_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digester', to='contenttypes.contenttype')),
                ('filter_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter', to='contenttypes.contenttype')),
                ('related_feeds', models.ManyToManyField(blank=True, related_name='digests', to='core.feed', verbose_name='Related Feeds')),
            ],
            options={
                'verbose_name': 'Digest',
                'verbose_name_plural': 'Digests',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='digest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='core.digest'),
        ),
    ]
