# Generated by Django 5.2.4 on 2025-07-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0021_check_empty_engines'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL Slug')),
                ('filter_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('filter_prompt', models.TextField(help_text='Custom prompt for filtering entries.', verbose_name='Filter Prompt')),
                ('last_filter', models.DateTimeField(blank=True, default=None, editable=False, help_text='Last time the filter was applied', null=True, verbose_name='Last Filter(UTC)')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Tokens Cost')),
                ('log', models.TextField(blank=True, default='', null=True, verbose_name='Log')),
                ('filter_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter', to='contenttypes.contenttype')),
                ('filtered_entries', models.ManyToManyField(blank=True, help_text='Entries selected by this filter', related_name='ai_filters', to='core.entry', verbose_name='Filtered Entries')),
                ('related_feeds', models.ManyToManyField(blank=True, related_name='ai_filters', to='core.feed', verbose_name='Related Feeds')),
            ],
            options={
                'verbose_name': 'AI Filter',
                'verbose_name_plural': 'AI Filter',
            },
        ),
    ]
