# Generated by Django 5.2.2 on 2025-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_entry_feed_digest_entry_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='digest_prompt',
            field=models.TextField(default='\nROLE: Professional News Editor\nTASK: Generate concise daily briefings\n\n# OUTPUT REQUIREMENTS\n1. FORMAT: Markdown with sections\n2. STRUCTURE:\n   ## {digest_name} | {date}\n   ### category\n   - **[Title](url)**  \n     summary\n\n# CONTENT RULES\n1. SOURCE PRIORITIZATION:\n   - Use existing AI summaries when provided\n   \n2. CATEGORIZATION:\n   - Auto-group articles into 3-5 topics\n\n3. STYLE GUIDELINES:\n   - Active voice, present tense\n   - Highlight:\n     • Novel research\n     • Practical implications\n     • Controversial claims\n   - Never repeat identical phrases\n\n', help_text='', verbose_name='Digest Prompt'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used for this digest', verbose_name='Total Tokens'),
        ),
    ]
