# Generated by Django 5.2.4 on 2025-07-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_filter_feed_filters_tagulous_filter_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='quality',
        ),
    ]
