# Generated by Django 5.2.4 on 2025-07-31 02:31

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_feed_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('is_ai', models.BooleanField(default=False, editable=False)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='API Key')),
                ('max_characters', models.IntegerField(default=5000)),
                ('server_url', models.URLField(blank=True, null=True, verbose_name='API URL(optional)')),
                ('proxy', models.URLField(blank=True, null=True, verbose_name='Proxy(optional)')),
            ],
            options={
                'verbose_name': 'DeepL',
                'verbose_name_plural': 'DeepL',
            },
        ),
        migrations.CreateModel(
            name='OpenAIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('is_ai', models.BooleanField(default=True, editable=False)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='API Key')),
                ('base_url', models.URLField(default='https://api.openai.com/v1', verbose_name='API URL')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='e.g. gpt-3.5-turbo, gpt-4-turbo', max_length=100)),
                ('title_translate_prompt', models.TextField(default='You are a professional, authentic translation engine. Translate only the text into {target_language}, return only the translations, do not explain the original text.', verbose_name='Title Translate Prompt')),
                ('content_translate_prompt', models.TextField(default='\nYou are a professional, authentic translation engine specialized in HTML content translation. \n\nRequirements:\n1. Translate only the text content into {target_language}\n2. Preserve ALL HTML tags, attributes, and structure completely unchanged\n3. Maintain proper context awareness across different HTML elements and their relationships\n4. Consider semantic meaning within nested tags and their hierarchical context\n5. Ensure translated text fits naturally within the HTML structure\n6. Keep inline elements (like <span>, <a>, <strong>) contextually coherent with their surrounding text\n7. Maintain consistency in terminology throughout the entire HTML document\n8. Return only the translated HTML content without explanations or comments\n\nImportant: Do not modify, remove, or alter any HTML tags, attributes, classes, IDs, or structural elements. Only translate the actual text content between tags.\n\n', verbose_name='Content Translate Prompt')),
                ('summary_prompt', models.TextField(default='Summarize the following text in {target_language} and return markdown format.')),
                ('temperature', models.FloatField(default=0.2)),
                ('top_p', models.FloatField(default=0.2)),
                ('frequency_penalty', models.FloatField(default=0)),
                ('presence_penalty', models.FloatField(default=0)),
                ('max_tokens', models.IntegerField(default=1000000)),
                ('rate_limit_rpm', models.IntegerField(default=0, help_text='Maximum requests per minute (0 = no limit)', verbose_name='Rate Limit (RPM)')),
            ],
            options={
                'verbose_name': 'OpenAI',
                'verbose_name_plural': 'OpenAI',
            },
        ),
        migrations.CreateModel(
            name='TestAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('translated_text', models.TextField(default='@@Translated Text@@')),
                ('max_characters', models.IntegerField(default=50000)),
                ('max_tokens', models.IntegerField(default=50000)),
                ('interval', models.IntegerField(default=3, verbose_name='Request Interval(s)')),
                ('is_ai', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
    ]
