# Generated by Django 5.2.4 on 2025-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_libretranslateagent_max_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libretranslateagent',
            name='max_characters',
            field=models.IntegerField(default=5000, help_text='Maximum characters per translation request', verbose_name='Max Characters'),
        ),
    ]
