# Generated by Django 5.2.4 on 2025-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_libretranslateagent_max_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libretranslateagent',
            name='server_url',
            field=models.URLField(default='https://libretranslate.com', help_text='Your self-hosted or public LibreTranslate server endpoint', verbose_name='Server URL'),
        ),
    ]
