# Generated by Django 5.2.4 on 2025-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_filterresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="deeplagent",
            name="log",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Log"
            ),
        ),
        migrations.AddField(
            model_name="openaiagent",
            name="log",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Log"
            ),
        ),
        migrations.AddField(
            model_name="testagent",
            name="log",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Log"
            ),
        ),
        migrations.AlterField(
            model_name="openaiagent",
            name="max_tokens",
            field=models.IntegerField(default=100000),
        ),
    ]
