# Generated by Django 5.2.4 on 2025-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_libretranslateagent'),
        ('core', '0029_deeplagent_log_openaiagent_log_testagent_log_and_more'),
    ]

    operations = [
    ]
