# Generated by Django 5.2.5 on 2025-08-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_libretranslateagent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiagent",
            name="max_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
