# Generated by Django 5.2.4 on 2025-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20250808_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='libretranslateagent',
            name='log',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Log'),
        ),
    ]
