# Generated by Django 5.2.5 on 2025-08-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_openaiagent_max_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                default="Unnamed Tag", max_length=255, verbose_name="Name"
            ),
        ),
    ]
