# Generated by Django 5.2.5 on 2025-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_openaiagent_max_tokens_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiagent',
            name='merge_system_prompt',
            field=models.BooleanField(default=False, help_text="Enable for models that don't support system system instructions (e.g., Gemma 3)", verbose_name='Merge System Prompt to User Message'),
        ),
    ]
