# Generated by Django 6.1.1 on 2026-09-16 02:14

import autoslug.fields
import core.models.tag
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_feed_feed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=core.models.tag.unicode_slugify, unique=True, verbose_name='URL Slug'),
        ),
    ]
