"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import tomllib


# from django.utils.crypto import get_random_string
from django.core.management.utils import get_random_secret_key
import os
import sys
from core.prompts import (
    DEFAULT_CONTENT_TRANSLATE_PROMPT,
    DEFAULT_FILTER_PROMPT,
    DEFAULT_SUMMARY_PROMPT,
    DEFAULT_TITLE_TRANSLATE_PROMPT,
    OUTPUT_FORMAT_FOR_FILTER_PROMPT,
)

SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
USER_MANAGEMENT = os.environ.get("USER_MANAGEMENT") == "1"
DEMO = os.environ.get("DEMO") == "1"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Read version from pyproject.toml
with open(BASE_DIR / "pyproject.toml", "rb") as f:
    pyproject = tomllib.load(f)
    VERSION = pyproject["project"]["version"]
LT_TIMEOUT=int(os.environ.get("LT_TIMEOUT", '5'))
SQLITE_TIMEOUT=float(os.environ.get("SQLITE_TIMEOUT", "30"))
OPENAI_API_TIMEOUT = float(os.environ.get("OPENAI_API_TIMEOUT", "120"))
OPENAI_API_MAX_RETRIES = max(0, int(os.environ.get("OPENAI_API_MAX_RETRIES", "0")))
# Custom User-Agent for fetching feeds. Empty = use built-in default.
RSS_FETCH_USER_AGENT = os.environ.get("RSS_FETCH_USER_AGENT", "")

X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "DENY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", get_random_secret_key())
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG") == "1"

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://*").split(",")
INTERNAL_IPS = [
    "127.0.0.1",
]
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = "django.contrib.sessions.backends.db"
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    "encrypted_model_fields",  # must set FIELD_ENCRYPTION_KEY value
    "tagulous",
]
DEBUG_PLUGINS = [
    "debug_toolbar",
    "bx_django_utils",  # https://github.com/boxine/bx_django_utils
]

SERIALIZATION_MODULES = {
    "xml": "tagulous.serializers.xml_serializer",
    "json": "tagulous.serializers.json",
    "python": "tagulous.serializers.python",
    "yaml": "tagulous.serializers.pyyaml",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
DEBUG_MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]
if DEBUG:
    INSTALLED_APPS += DEBUG_PLUGINS
    MIDDLEWARE += DEBUG_MIDDLEWARE


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.version",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATA_FOLDER = BASE_DIR / "data"
DATA_FOLDER.mkdir(exist_ok=True)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_FOLDER / "db.sqlite3",
        "OPTIONS": {
            "timeout": SQLITE_TIMEOUT,
        },
    }
}

if not DEBUG and "test" not in sys.argv:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/1"),
            "OPTIONS": {
                # Timeout for establishing a connection in seconds
                "socket_connect_timeout": 5,
                # Timeout for read/write operations in seconds
                "socket_timeout": 5,
                # Maximum number of connections in the pool
                "max_connections": 100,
            },
            # Default timeout for cache keys (1 day).
            # Keys without an expiration date will be cleaned up,
            # and expired keys are cleaned up periodically by Redis.
            "TIMEOUT": 60 * 60 * 24,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
LANGUAGES = [
    ("zh-hans", "简体中文"),
    ("en-us", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]


TIME_ZONE = os.environ.get("TIME_ZONE", "UTC") # Asia/Shanghai,America/New_York,Europe/London

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_BACKEND = "whitenoise.storage.CompressedManifestStaticFilesStorage"
if "test" in sys.argv:
    STATICFILES_BACKEND = "django.contrib.staticfiles.storage.StaticFilesStorage"

STORAGES = {
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# https://pypi.org/project/django-encrypted-model-fields/
FIELD_ENCRYPTION_KEY = "RWdGiEq3LgOf3Tyt3ALlEnxUkIlL4wS2dCDBe_sLWWo="

DEFAULT_TARGET_LANGUAGE = os.environ.get(
    "DEFAULT_TARGET_LANGUAGE", "Chinese Simplified"
)
TRANSLATION_LANGUAGES = [
    ("English", "English"),
    ("Chinese Simplified", "Chinese Simplified"),
    ("Chinese Traditional", "Chinese Traditional"),
    ("Russian", "Russian"),
    ("Japanese", "Japanese"),
    ("Korean", "Korean"),
    ("Czech", "Czech"),
    ("Danish", "Danish"),
    ("German", "German"),
    ("Spanish", "Spanish"),
    ("French", "French"),
    ("Indonesian", "Indonesian"),
    ("Italian", "Italian"),
    ("Hungarian", "Hungarian"),
    ("Norwegian Bokmal", "Norwegian Bokmal"),
    ("Dutch", "Dutch"),
    ("Polish", "Polish"),
    ("Portuguese", "Portuguese"),
    ("Swedish", "Swedish"),
    ("Turkish", "Turkish"),
]
LOG_LEVEL = os.environ.get(
    "LOG_LEVEL", "ERROR"
)  # DEBUG > INFO > WARNING > ERROR > CRITICAL
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            # "format": "{levelname} {asctime} {message:.500s}", 限制500字符
            "format": "{levelname} {asctime}<{name}>:{message}",
            "style": "{",
        },
    },
    "handlers": {
        "logfile": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": DATA_FOLDER / "app.log",
            "maxBytes": 1024 * 1024 * 5,  # 10 MB
            "encoding": "utf-8",
            "backupCount": 2,
            "formatter": "verbose",
        },
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["logfile", "console"],
        "level": LOG_LEVEL,
    },
}

default_title_translate_prompt = DEFAULT_TITLE_TRANSLATE_PROMPT
default_content_translate_prompt = DEFAULT_CONTENT_TRANSLATE_PROMPT
default_summary_prompt = DEFAULT_SUMMARY_PROMPT
default_filter_prompt = DEFAULT_FILTER_PROMPT
output_format_for_filter_prompt = OUTPUT_FORMAT_FOR_FILTER_PROMPT
