# Generated by Django 5.2.2 on 2025-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0045_alter_openaitranslator_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtranslator',
            name='max_tokens',
            field=models.IntegerField(default=50000),
        ),
    ]
