# Generated by Django 5.2.2 on 2025-07-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0046_testtranslator_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaitranslator',
            name='rate_limit_rpm',
            field=models.IntegerField(default=0, help_text='Maximum requests per minute (0 = no limit)', verbose_name='Rate Limit (RPM)'),
        ),
    ]
